#pragma once

/// @file
/// @brief Umbrella for the split UE SDK: includes every ue/sdk/<Type>.h in dependency
/// order (Fwd -> Enums -> Values, then the UObject / actor / component graph). This is
/// the generated, machine-derived surface; treat it as an opaque dependency. Prefer
/// including ue/Engine.h (which pulls this in plus the custom helpers and namespace Engine)
/// over including individual sdk/ headers.

#include "sdk/Fwd.h"
#include "sdk/Enums.h"
#include "sdk/Values.h"

#include "sdk/UObject.h"
#include "sdk/UField.h"
#include "sdk/UStruct.h"
#include "sdk/UClass.h"
#include "sdk/UFunction.h"
#include "sdk/AActor.h"
#include "sdk/AController.h"
#include "sdk/APawn.h"
#include "sdk/ACharacter.h"
#include "sdk/APortalWarsCharacter.h"
#include "sdk/ACharacterSkin.h"
#include "sdk/AInfo.h"
#include "sdk/APlayerState.h"
#include "sdk/APortalWarsPlayerState.h"
#include "sdk/AHUD.h"
#include "sdk/APlayerController.h"
#include "sdk/ACullableActor.h"
#include "sdk/ABaseGun.h"
#include "sdk/AGun.h"
#include "sdk/ULevel.h"
#include "sdk/UGameInstance.h"
#include "sdk/UPortalWarsGameInstance.h"
#include "sdk/UPlayer.h"
#include "sdk/ULocalPlayer.h"
#include "sdk/UPortalWarsLocalPlayer.h"
#include "sdk/USaveGame.h"
#include "sdk/UPortalWarsSaveGame.h"
#include "sdk/APlayerCameraManager.h"
#include "sdk/UActorComponent.h"
#include "sdk/USceneComponent.h"
#include "sdk/UPrimitiveComponent.h"
#include "sdk/UMeshComponent.h"
#include "sdk/USkinnedMeshComponent.h"
#include "sdk/USkeletalMeshComponent.h"
#include "sdk/UStaticMeshComponent.h"
#include "sdk/UWorld.h"
#include "sdk/UFont.h"
#include "sdk/UCanvas.h"
#include "sdk/UScriptViewportClient.h"
#include "sdk/UGameViewportClient.h"
#include "sdk/UBlueprintFunctionLibrary.h"
#include "sdk/UGameplayStatics.h"
#include "sdk/UEngine.h"
#include "sdk/UInputSettings.h"
#include "sdk/UConsole.h"
#include "sdk/UKismetStringLibrary.h"
#include "sdk/UKismetTextLibrary.h"
#include "sdk/UPortalWarsNotificationManager.h"
#include "sdk/APortalWarsBasePlayerController.h"
#include "sdk/APortalWarsPlayerController.h"
#include "sdk/UNetConnection.h"
#include "sdk/UNetDriver.h"
