#pragma once

/// @file
/// @brief Forward declarations and standard includes for the split Engine SDK.
/// Included by every sdk/ header; the umbrella <Engine.h> pulls the whole SDK together.

#include <Windows.h>
#include <cstdint>
#include <string>
#include <vector>
#include <iostream>

struct FNameEntryHandle;
struct FNameEntry;
struct FNamePool;
struct FName;
struct FTextData;
struct FText;
struct UObject;
struct UField;
struct UStruct;
struct UClass;
struct UFunction;
struct TUObjectArray;
template <class T>
struct TArray;
struct FString;
struct FColor;
struct FLinearColor;
struct FMatrix;
struct FVector2D;
struct FVector;
struct FRotator;
struct FQuat;
struct FTransform;
struct FRecoilData;
struct FMulticastInlineDelegate;
struct AActor;
struct AController;
struct APawn;
struct ACharacter;
struct APortalWarsCharacter;
struct ACharacterSkin;
struct FPlayerStatsInfo;
struct FPlayerStatsInfo_InDepth;
struct FUserRankInfo;
struct FEquippedCustomizations;
struct AInfo;
struct APlayerState;
struct APortalWarsPlayerState;
struct AHUD;
struct APlayerController;
struct FWeaponData;
struct ACullableActor;
struct ABaseGun;
struct FAutoAimData;
struct FShotInfo;
struct FFuzzyConfig;
struct AGun;
struct ULevel;
struct UGameInstance;
struct UPortalWarsGameInstance;
struct UPlayer;
struct ULocalPlayer;
struct UPortalWarsLocalPlayer;
struct USaveGame;
struct UPortalWarsSaveGame;
struct FMinimalViewInfo;
struct FCameraCacheEntry;
struct FTViewTarget;
struct APlayerCameraManager;
struct FHitResult;
struct UActorComponent;
struct USceneComponent;
struct UPrimitiveComponent;
struct UMeshComponent;
struct USkinnedMeshComponent;
struct USkeletalMeshComponent;
struct UStaticMeshComponent;
struct UWorld;
struct UFont;
struct UCanvas;
struct UScriptViewportClient;
struct UGameViewportClient;
struct UBlueprintFunctionLibrary;
struct UGameplayStatics;
struct FSoftObjectPath;
struct FFloatRangeBound;
struct FFloatRange;
struct FSoftClassPath;
struct FDirectoryPath;
struct FFrameRate;
struct UEngine;
struct FKey;
struct UInputSettings;
struct UConsole;
struct UKismetStringLibrary;
struct UKismetTextLibrary;
struct FGameplayTag;
struct FErrorInfo;
struct FErrorData;
struct UPortalWarsNotificationManager;
struct APortalWarsBasePlayerController;
struct FUniqueNetIdWrapper;
struct FUniqueNetIdRepl;
struct FTextChatData;
struct APortalWarsPlayerController;
struct UNetConnection;
struct UNetDriver;
